### ISSUE TITLE
`requires` associate lacking proper order

### ISSUE THREAD

**Issue by leonkozlowski** [thejig/jiggy#16]
`.yml` `requires` not perfect in setting order

**Comment by leonkozlowski** [comment]
This falls into the `Graph` research and traversing thru pipeline in proper sequence

**Comment by mitchbregs** [comment]
Keeping some thoughts here:

https://stackoverflow.com/questions/25054003/how-to-convert-a-nested-ordereddict-to-dict

**Comment by leonkozlowski** [comment]
resolved
